### ISSUE TITLE
project : specifying module name before issue title

### ISSUE THREAD

**Issue by ha90** [gauravmunjal13/Indexed_search#11]
Hi, lets specify the module name before each issue like this:
    storage : issue description
We have the following modules
app
indexingEngine  <--- need to change this to indexing_engine
storage
utils
test
gui
project           <-- use this when scope is project wide

Please tell if we need any other scope.

**Comment by ha90** [comment]
Or we could also specify like this : 
[app] Issue description. 
This also looks good. Please confirm.

**Comment by gauravmunjal13** [comment]
yes. [module] is fine. Even as a commit message.

**Comment by ha90** [comment]
Ok
