### ISSUE TITLE
[project] Design discussion

### ISSUE THREAD

**Issue by ha90** [gauravmunjal13/Indexed_search#15]
It seems we have a gap in our design approaches from the start (requirement phase) which has only materialized in the coding phase. This emphasizes the need to have more thorough discussions in both requirement and design phase, so that the coding phase is not affected by major requirement/design changes. Currently, the issue at hand is as follows:-

What our application will do and how it will do it:-
Approach 1 : User specifies the location in which he wants to search a query.
Approach 2 : User only specifies the search query and the application takes locations that the user
                     wants to index (once at the time of installation and other times though GUI).
                     Approach 2a : Application will only search the query in the indexed locations.
                     Approach 2b : Application will search the query everywhere (*elaborate)
Other things we may need to take care of:-

> Removing indexing
> Merging indexes

Lets discuss on this. Please use this comment to reply inline.

**Comment by gauravmunjal13** [comment]
I think we should go for the second approach for time being. Being specific, Approach 2a.
Removing indexed folder is in progress.

For second version, we will implement it via Approach 1. It will need merging indexes.

**Comment by ha90** [comment]
ok
