### ISSUE TITLE
[indexing_engine] As per latest design discussion, indexing module interface will change.

### ISSUE THREAD

**Issue by ha90** [gauravmunjal13/Indexed_search#16]
Indexing engine module will now have the below interfaces:
1. add_index(directory) - this will add the directory to the index. 
2.  remove_index(directory) - this will remove the directory from the index. 
3. search(word) - this will search the word in the index.

Note. 
a. Now indexing engine module will be responsible for calling save (currently being done by app module)
b. Function names can be changed as per liking.

**Comment by gauravmunjal13** [comment]
Done points: 1,2 and 3

For "Note - a":  I tried to call save on **del** attribute. But it was giving some error. 
Closing this now and raising another issue for saving the file.
