### ISSUE TITLE
[index_module] [app]: Cleaning indexed data

### ISSUE THREAD

**Issue by gauravmunjal13** [gauravmunjal13/Indexed_search#17]
There should be a support for cleaning the indexed data.

**Comment by ha90** [comment]
Ok, a function that will do the same work as remove_index(directory) but for the whole index

**Comment by gauravmunjal13** [comment]
I think this should be managed as communication between app and manager. Whats your say?

**Comment by ha90** [comment]
index module will provide a function right? like clean_all_index() since its managing all the indexing..app will just call this api based on user input

**Comment by gauravmunjal13** [comment]
There can be following two approach for this:
1) If it is expected that app should communicate to file_manager module via index_module, then index_module should have a clean_all_index() method. 

I think this shouldn't be the case. As for this purpose app can directly communicate to file_manager to clean the indexed file. Hence, from this the following approach:
The app should call the file_manager to clean all the indexed data.

**Comment by gauravmunjal13** [comment]
Implemented in commit: a8d1c27c6bc9e234c273e97c7636057ceec28b51
