### ISSUE TITLE
[app] argparse add_mutually_exclusive_group

### ISSUE THREAD

**Issue by gauravmunjal13** [gauravmunjal13/Indexed_search#20]
"parser.add_mutually_exclusive_group()"
Search and Indexing operations are not conflicting each other. Means they can be done together.
So not required the above line of code.

**Comment by gauravmunjal13** [comment]
I think it would be like:
either index or de-index or clean_index : as optional but mutually exclusive arguments. So can be grouped together.
Left with search as optional argument. But it comes irrelevant if clean_index flag is set. So better to be grouped with above group.

Please provide comments otherwise close it.

**Comment by ha90** [comment]
Yes, search and index will be different options. Closing the issue.
