### ISSUE TITLE
Naming convention: Lets use a common convention

### ISSUE THREAD

**Issue by gauravmunjal13** [gauravmunjal13/Indexed_search#4]
There is a mixing of naming convention in variables names, function names and class names.
Like either use "naming_convention" or camel case "namingConvention"

I think we should go for following conventions:
1) for classes:we use camelCase convention to improve readability. 
     Like: def ClassName
2) for functions:
     Like: def func_name
3) for local variables: same as functions 
4) for global variables: start the variable name with an underscore.
     Like: "_global_var"

Please have your suggestions on this. Assigned to both of us.

**Comment by ha90** [comment]
Lets follow the naming convention described here:-
https://www.python.org/dev/peps/pep-0008/#naming-conventions

All the points are same except point 1.
1. For classes:- CapWords eg. MyClass

**Comment by gauravmunjal13** [comment]
Point one is also same: like "ClassName".
So closing this issue.
